// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApJ6XE57e9YOpHszBL17qR4NHKXbs3ufY',
    appId: '1:254031159338:web:ad33c0bd51ff37b9c36353',
    messagingSenderId: '254031159338',
    projectId: 'dicoding-chatting-c5882',
    authDomain: 'dicoding-chatting-c5882.firebaseapp.com',
    storageBucket: 'dicoding-chatting-c5882.appspot.com',
    measurementId: 'G-FLPSTM02SB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXJ9Ip0g9uKpQvCz1U_5c8hvn6134Vshc',
    appId: '1:254031159338:android:ecb6293e063573a2c36353',
    messagingSenderId: '254031159338',
    projectId: 'dicoding-chatting-c5882',
    storageBucket: 'dicoding-chatting-c5882.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGdW-CP0cysGfksAvzJMDd-iNarztxTcA',
    appId: '1:254031159338:ios:10a63dabeb27513dc36353',
    messagingSenderId: '254031159338',
    projectId: 'dicoding-chatting-c5882',
    storageBucket: 'dicoding-chatting-c5882.appspot.com',
    iosClientId: '254031159338-ei1csg50vc4fdb9ltk7ptgo70cg8fno9.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.dicodingChatting',
  );
}
